DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS genre;

CREATE TABLE IF NOT EXISTS genre
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1),
    name character varying(30) NOT NULL,
    CONSTRAINT genre_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    name text NOT NULL,
    year integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    CONSTRAINT film_pkey PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id integer NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_id FOREIGN KEY (film_id)
        REFERENCES film (id) MATCH SIMPLE,
    CONSTRAINT fk_genre_id FOREIGN KEY (genre_id)
        REFERENCES genre (id) MATCH SIMPLE
);

INSERT INTO genre (name) VALUES ('Drama');
INSERT INTO genre (name) VALUES ('Comedy');
INSERT INTO genre (name) VALUES ('Horror');
INSERT INTO genre (name) VALUES ('Romance');
INSERT INTO genre (name) VALUES ('Fantasy');
INSERT INTO genre (name) VALUES ('Action');
INSERT INTO genre (name) VALUES ('Mystery');

INSERT INTO film (name, year) VALUES ('Titanic', 1997);
INSERT INTO film (name, year) VALUES ('Forest Gump', 1994);
INSERT INTO film (name, year) VALUES ('Home Alone', 1990);
INSERT INTO film (name, year) VALUES ('Saw', 2004);
INSERT INTO film (name, year) VALUES ('Bridget Jones''s Diary', 2001);
INSERT INTO film (name, year) VALUES ('Transformers', 2007);
INSERT INTO film (name, year) VALUES ('Taxi', 1998);
INSERT INTO film (name, year) VALUES ('Sherlock Holmes', 2009);
INSERT INTO film (name, year) VALUES ('Sherlock Holmes', 2009);

INSERT INTO film_genre (film_id, genre_id)
VALUES (1, 1),
       (2, 1),
       (3, 2),
       (4, 3),
       (5, 4),
       (6, 5),
       (7, 6),
       (8, 6),
       (8, 7);